### ISSUE TITLE
extend=hourly chnaged?

### ISSUE THREAD

**Issue by pdxvr** [alexander0042/pirateweather#109] opened 2023-09-28 23:20 UTC
Starting this morning, I haven't changed anything, but it's only retrieving 48 hours of forecast instead of 168.

**Comment by alexander0042** [comment] 2023-09-29 01:22
Apologies for this! Same issue as #108, with the root cause being how my fallback proxy parsed the URL when my main AWS region went down. Fix has been deployed (despite AWS still not working), but let me know if the issue is still happeing

**Closed** 2023-11-07 21:19 UTC
