### ISSUE TITLE
Bug: Temperatures are reportet in °F instead of °C

### ISSUE THREAD

**Issue by msinn** [alexander0042/pirateweather#71] opened 2023-06-11 10:11 UTC
The api documentation states, that the temperatures are reported in °C (and in the pastbthey were). Now temperatures (at least formthe current conditions) are reported in °F

**Comment by msinn** [comment] 2023-06-12 15:40
I  had right temperatures in my home automation and without any modifications on my side they switched to °F. I cannot say when it happended.

Btw.: I call the api to get metric units and windspeeds are reported in km/h.

**Comment by alexander0042** [comment] 2023-06-12 15:42
Ok, that helps! So you're using the HACS Pirate Weather Integration?

**Comment by msinn** [comment] 2023-06-12 15:44
You lost me. What is HACS?

**Comment by msinn** [comment] 2023-06-12 16:27
I am one of the core developers of an smarthome integration system called SmartHomeNG. I wrote a plugin for darksky and created a modified version of it for pirateweather as darksky was shutting down.

**Comment by msinn** [comment] 2023-06-13 21:04
I am using **ca** as units when calling the pirateweather api

`ca: SI, with Wind Speed and Wind Gust in kilometres per hour. `

**Comment by papauschek** [comment] 2023-06-14 06:50
I see the same behavior. I am passing "ca" as the units value and was - until recently - getting C° returned. Since 1 or 2 days, this has changed to F°. How to get back to C° ?

**Comment by alexander0042** [comment] 2023-06-14 12:20
OK. so definitely something going on here, but it's tricky for me to reproduce. Do you mind passing along the URL string that you're passing with the API Key redacted?

**Comment by papauschek** [comment] 2023-06-14 21:13
Very strange. I cannot seem to reproduce it on my local development setup. The issue happens only on my raspberry pi (Chromium browser). Is it possible that certain request headers / browser headers can override the units parameter?

I will try to get an exact request/response log with the actual headers to try and reproduce the issue, but might not get around to it until later this week.

**Comment by papauschek** [comment] 2023-06-15 06:26
Now its back to C°. Sorry could not reproduce it anymore. If it happens again, I'll try. :D

**Comment by alexander0042** [comment] 2023-06-19 15:05
Thanks for the update! I'm going to close this for now to keep things tidy, but please feel free to re-open if it crops up again

**Closed by alexander0042** 2023-06-19 15:05 UTC
